### ISSUE TITLE
항체의약품 투여경로 예시

### ISSUE THREAD

**Issue by shanmdphd** [pipetcpt/pharmapk#12]
최수인 선생님, 

아래 글 읽고 예가 적절한 것인지 검토해 주세요. LHRH는 항체의약품이 아니라서 헷깔릴 수 있어 보입니다~

`06.Rmd` 119행입니다.

> 항체의약품의 또다른 특이한 점은 투여 경로에 따라 제제의 작용이 상이할 수 있는 점이다. 예를 들어, LHRH는 정맥 내 투여의 경우 LH와 FSH의 분비를 촉진하지만 근육 또는 피하 투여의 경우 LH와 FSH의 분비를 억제하게 된다. 따라서 항체의약품 개발 시에는 제제의 개발 목적에 맞는 적절한 투여 경로를 고려해야 한다.

댓글로 남겨주시거나, 직접 코드 수정해서 commit & push 해 주셔도 좋을듯요.
만약 항체의약품에서 예를 찾기 어려우면 호르몬제의 예를 사용한다고 언급하면서 full name도 기재해주면 좋겠습니다. (Luteinizing Hormone Releasing Hormone)

**Comment by sueinchoi** [comment]
좋은 지적이시네요. Protein drug에 대한 설명인대 항체의약품 내용에 잘못 낀거같아요 감사합니다. 수정해서 push 했습니다

**Comment by shanmdphd** [comment]
감사합니다
